"""Original, deterministic equipment pixels for the sunny quarantine town.

Inventory / pickup icons stay 24 x 24; the target stays 32 x 48.
Held weapons have separate sprites generated by build_held_weapons.py.
"""

from pathlib import Path

from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "assets" / "pixel" / "items"
INK = "#293a49"
METAL = "#7193a1"
STEEL = "#bdd2cc"
RIM = "#eff0ce"
GOLD = "#e6b46c"
WOOD = "#c18159"
WOOD_SHADE = "#83533e"


def _crowbar(d):
    d.line([(3, 16), (16, 13), (20, 10), (20, 7), (17, 6), (15, 8)], fill=INK, width=5)
    d.line([(3, 15), (16, 12), (19, 10), (19, 7), (17, 7), (16, 8)], fill=METAL, width=3)
    d.line([(3, 14), (15, 11), (18, 9), (18, 7)], fill=STEEL)
    d.point((17, 7), fill=RIM)
    d.line((5, 14, 10, 13), fill="#bf6d59", width=3)
    d.line((5, 13, 10, 12), fill="#e89b77")
    for x, y in ((5, 15), (7, 14), (9, 14)):
        d.point((x, y), fill=WOOD_SHADE)
    d.line((2, 16, 4, 16), fill=RIM)


def _pistol(d):
    d.polygon([(3, 8), (6, 7), (21, 7), (22, 8), (22, 12),
               (14, 12), (14, 16), (10, 16), (9, 20), (4, 20),
               (6, 12), (3, 12)], fill=INK)
    d.rectangle((4, 8, 20, 10), fill=METAL)
    d.line((5, 8, 20, 8), fill=RIM)
    d.line((6, 11, 18, 11), fill="#4c6e7f")
    for x in (6, 8):
        d.line((x, 9, x, 10), fill=INK)
    d.rectangle((19, 9, 21, 10), fill=STEEL)
    d.point((21, 10), fill=INK)
    d.point((19, 6), fill=GOLD)
    d.polygon([(7, 12), (11, 12), (9, 18), (6, 18)], fill=WOOD)
    d.line((8, 13, 6, 17), fill=GOLD)
    d.line((9, 14, 8, 17), fill=WOOD_SHADE)
    d.point((11, 13), fill=STEEL)
    d.line((11, 15, 12, 15), fill=METAL)
    d.point((12, 13), fill=INK)


def _shotgun(d):
    d.polygon([(1, 12), (5, 11), (10, 10), (11, 8), (23, 8),
               (23, 12), (19, 13), (18, 15), (10, 15), (5, 19),
               (1, 18)], fill=INK)
    d.line((10, 9, 22, 9), fill=RIM)
    d.line((10, 10, 22, 10), fill=METAL)
    d.line((11, 12, 21, 12), fill=STEEL)
    d.polygon([(2, 13), (7, 12), (10, 12), (9, 14), (4, 17),
               (2, 17)], fill=WOOD)
    d.line((3, 13, 8, 12), fill=GOLD)
    d.line((3, 16, 7, 14), fill=WOOD_SHADE)
    d.rectangle((13, 12, 18, 14), fill=WOOD)
    d.line((13, 12, 18, 12), fill=GOLD)
    for x in (14, 16, 18):
        d.point((x, 14), fill=WOOD_SHADE)
    d.point((21, 7), fill=WOOD)


def _ammo(d):
    # Three brass cartridges sit in a folded teal cardboard box.
    d.polygon([(3, 9), (6, 6), (19, 6), (22, 9), (21, 20),
               (3, 20)], fill=INK)
    d.rectangle((4, 9, 20, 18), fill="#659c8a")
    d.polygon([(4, 9), (7, 7), (18, 7), (20, 9)], fill="#a0c5a4")
    d.rectangle((17, 10, 20, 18), fill="#49786f")
    for x in (6, 11, 16):
        d.rectangle((x, 4, x + 3, 10), fill=INK)
        d.rectangle((x + 1, 4, x + 2, 8), fill=GOLD)
        d.point((x + 1, 3), fill="#be8650")
        d.line((x + 1, 5, x + 1, 8), fill=RIM)
        d.line((x + 1, 9, x + 2, 9), fill="#ae793f")
    d.rectangle((6, 12, 15, 16), fill="#e8ddb1")
    d.rectangle((7, 13, 9, 14), fill="#526b64")
    d.point((9, 15), fill="#526b64")
    d.line((11, 13, 11, 15), fill="#526b64")
    d.line((13, 13, 13, 15), fill="#526b64")
    d.line((4, 18, 19, 18), fill="#9cbea0")


def _shells(d):
    for x, y in ((3, 7), (10, 4), (17, 6)):
        d.rectangle((x, y, x + 4, y + 14), fill=INK)
        d.rectangle((x + 1, y + 1, x + 3, y + 10), fill="#bd6858")
        d.line((x + 1, y + 2, x + 1, y + 9), fill="#efac80")
        d.line((x + 3, y + 2, x + 3, y + 9), fill="#9e514c")
        d.rectangle((x + 1, y + 11, x + 3, y + 13), fill=GOLD)
        d.line((x + 1, y + 11, x + 1, y + 13), fill=RIM)
        d.point((x + 2, y + 1), fill="#e59d76")


def _medkit(d):
    d.rectangle((8, 3, 16, 6), fill=INK)
    d.line((10, 4, 14, 4), fill=STEEL)
    d.polygon([(4, 6), (20, 6), (22, 8), (22, 19),
               (20, 21), (4, 21), (2, 19), (2, 8)], fill=INK)
    d.rectangle((4, 8, 20, 18), fill="#e9dfb7")
    d.line((5, 7, 19, 7), fill=RIM)
    d.rectangle((19, 9, 20, 18), fill="#b6b994")
    d.line((5, 19, 19, 19), fill="#a1ae99")
    for x in (5, 18):
        d.rectangle((x, 7, x + 1, 9), fill="#7b978f")
        d.rectangle((x, 17, x + 1, 19), fill="#7b978f")
    d.rectangle((10, 10, 13, 17), fill="#c16658")
    d.rectangle((8, 12, 15, 15), fill="#c16658")
    d.line((10, 10, 12, 10), fill="#e88e6d")
    d.point((4, 10), fill=RIM)


def _target():
    image = Image.new("RGBA", (32, 48))
    d = ImageDraw.Draw(image)
    d.ellipse((3, 41, 29, 47), fill=(39, 69, 77, 80))
    d.polygon([(13, 26), (18, 26), (18, 41), (27, 43),
               (27, 45), (4, 45), (4, 43), (13, 41)], fill=INK)
    d.rectangle((14, 30, 16, 42), fill=WOOD)
    d.line((14, 32, 14, 41), fill=GOLD)
    d.line((6, 43, 25, 43), fill=STEEL)
    d.line((7, 44, 13, 44), fill=METAL)
    # A cut-out practice dummy on a painted support: warm paper, blue target.
    outline = [(12, 3), (20, 3), (23, 6), (24, 10), (22, 15),
               (20, 17), (25, 19), (27, 23), (27, 33), (5, 33),
               (5, 23), (7, 19), (12, 17), (9, 14), (8, 8), (9, 5)]
    d.polygon(outline, fill=INK)
    inner = [(12, 5), (19, 5), (21, 7), (22, 10), (20, 14),
             (18, 17), (19, 19), (24, 21), (25, 24), (25, 31),
             (7, 31), (7, 24), (9, 21), (14, 19), (14, 16),
             (11, 13), (10, 9), (11, 6)]
    d.polygon(inner, fill="#d7c79b")
    d.line((12, 5, 19, 5), fill=RIM)
    d.line((8, 23, 8, 29), fill="#f3e5b9")
    d.polygon([(20, 6), (22, 10), (20, 14), (18, 17), (19, 19),
               (24, 21), (25, 24), (25, 31), (22, 31), (22, 23),
               (17, 19), (17, 16), (19, 12)], fill="#bba67e")
    d.ellipse((11, 6, 21, 16), outline="#7c918b")
    d.ellipse((8, 19, 24, 32), fill="#5e9698")
    d.ellipse((11, 21, 21, 30), outline="#d4dcc0")
    d.ellipse((14, 23, 18, 27), fill="#de8a62")
    d.point((16, 25), fill="#ffda91")
    d.line((15, 9, 17, 9), fill="#758e85")
    d.line((16, 8, 16, 12), fill="#758e85")
    for x, y in ((11, 23), (20, 28), (13, 12)):
        d.point((x, y), fill=INK)
        d.point((x + 1, y + 1), fill=RIM)
    d.line((9, 32, 23, 32), fill=METAL)
    return image


def main():
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for name, draw in (("crowbar", _crowbar), ("pistol", _pistol),
                       ("shotgun", _shotgun), ("ammo_9mm", _ammo),
                       ("shells", _shells), ("medkit", _medkit)):
        image = Image.new("RGBA", (24, 24))
        draw(ImageDraw.Draw(image))
        image.save(OUTPUT / f"{name}.png")
    _target().save(OUTPUT / "training_target.png")
    print("Built six item icons and a training target.")


if __name__ == "__main__":
    main()
